sge/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from sge.source import views as vw

urlpatterns = patterns('',
	url(r'^$', 'django.contrib.auth.views.login', name='auth_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {"next_page": "/"}, name='auth_logout'),

    url(r'^mudar_senha/$', 'django.contrib.auth.views.password_change',
        {'template_name': 'source/mudar_senha.html'}, name='source_mudar_senha'),
    url(r'^mudar_senha/concluido/$', 'django.contrib.auth.views.password_change_done',
        {'template_name': 'source/mudar_senha_concluido.html'}, name='source_mudar_senha_concluido'),

    url(r'^cidades-uf$', vw.CidadeListView.as_view(), name='source_cidades_uf'),
    url(r'^cliente/detail$', vw.ClienteDetailView.as_view(), name='source_cliente_detail'),
    url(r'^entregador/listar-clientes$', vw.EntregadorClienteListView.as_view(), name='source_entregador_cliente'),
    url(r'^entregador-cliente/valor$', vw.EntregadorClienteDetailView.as_view(), name='source_entregador_cliente_detail'),

	url(r'^painel-controle/$', vw.PainelControleView.as_view(), name='source_painel_controle'),
    url(r'^perfil/alteracao/(?P<pk>\d+)$', vw.PerfilEditarView.as_view(), name='source_perfil_alteracao'),

    url(r'^cliente/inclusao$', vw.ClienteInclusaoView.as_view(), name='source_cliente_inclusao'),
    url(r'^cliente/consulta$', vw.ClienteConsultaView.as_view(), name='source_cliente_consulta'),
    url(r'^cliente/alteracao/(?P<pk>\d+)$', vw.ClienteAlteracaoView.as_view(), name='source_cliente_alteracao'),
    url(r'^cliente/status-change/(?P<pk>\d+)/(?P<status>[0,1])$', vw.ClienteStatusChangeView.as_view(), name='source_cliente_status_change'),
    
    url(r'^entregador/inclusao$', vw.EntregadorInclusaoView.as_view(), name='source_entregador_inclusao'),
    url(r'^entregador/consulta$', vw.EntregadorConsultaView.as_view(), name='source_entregador_consulta'),
    url(r'^entregador/alteracao/(?P<pk>\d+)$', vw.EntregadorAlteracaoView.as_view(), name='source_entregador_alteracao'),
    url(r'^entregador/status-change/(?P<pk>\d+)/(?P<status>[0,1])$', vw.EntregadorStatusChangeView.as_view(), name='source_status_change'),

    url(r'^locomocao/inclusao$', vw.LocomocaoInclusaoView.as_view(), name='source_locomocao_inclusao'),
    url(r'^locomocao/consulta$', vw.LocomocaoConsultaView.as_view(), name='source_locomocao_consulta'),
    url(r'^locomocao/alteracao/(?P<pk>\d+)$', vw.LocomocaoAlteracaoView.as_view(), name='source_locomocao_alteracao'),
    url(r'^locomocao/pendente/(?P<pk>\d+)$', vw.LocomocaoPendenteView.as_view(), name='source_locomocao_pendente'),

    url(r'^entrega/inclusao$', vw.EntregaInclusaoView.as_view(), name='source_entrega_inclusao'),
    url(r'^entrega/consulta$', vw.EntregaConsultaView.as_view(), name='source_entrega_consulta'),
    url(r'^entrega/alteracao/(?P<pk>\d+)$', vw.EntregaAlteracaoView.as_view(), name='source_entrega_alteracao'),
    url(r'^entrega/cancelar/(?P<pk>\d+)$', vw.EntregaCancelamentoView.as_view(), name='source_entrega_cancelamento'),

    url(r'^transferencia/inclusao$', vw.TransferenciaInclusaoView.as_view(), name='source_transferencia_inclusao'),
    url(r'^transferencia/consulta$', vw.TransferenciaConsultaView.as_view(), name='source_transferencia_consulta'),
    url(r'^transferencia/alteracao/(?P<pk>\d+)$', vw.TransferenciaAlteracaoView.as_view(), name='source_transferencia_alteracao'),
    url(r'^transferencia/cancelar/(?P<pk>\d+)$', vw.TransferenciaCancelamentoView.as_view(), name='source_transferencia_cancelamento'),
)

sge/source/models.py
# -*- coding: utf-8 -*-

import choices

from datetime import date
from decimal import Decimal

from django.db import models

__all__ = ('Cidade', 'Cliente', 'Produto', 'Entregador',
		   'EntregadorCliente', 'Locomocao', 'Entrega',
		   'EntregaCliente', 'Transferencia', 'TransferenciaCliente')


class CurrencyField(models.DecimalField):
	__metaclass__ = models.SubfieldBase

	def to_python(self, value):
		try:
			return super(CurrencyField, self).to_python(value).quantize(Decimal("0.01"))
		except AttributeError:
			return None


class Cidade(models.Model):
	codigo_cidade =  models.CharField(primary_key=True, max_length=10, verbose_name='Código do município')
	uf = models.CharField(max_length=2, verbose_name='UF da cidade', choices=choices.ESTADOS)
	nome = models.CharField(max_length=200, verbose_name='Nome da cidade')

	def __unicode__(self):
		return self.nome


class Cliente(models.Model):
	cnpj = models.CharField(max_length=20, verbose_name='CNPJ', blank=True, null=True)
	razao_social = models.CharField(max_length=120, verbose_name='Razão social')
	end_rua = models.CharField(max_length=120, verbose_name='Logradouro')
	end_numero = models.CharField(max_length=10, verbose_name='Número', blank=True, null=True)
	end_complemento = models.CharField(max_length=100, verbose_name='Complemento', blank=True, null=True)
	end_bairro = models.CharField(max_length=80, verbose_name='Bairro', blank=True, null=True)
	end_estado = models.CharField(max_length=2, verbose_name='Estado', choices=choices.ESTADOS)
	end_cidade = models.ForeignKey(Cidade, verbose_name='Cidade', blank=True, null=True)
	email = models.CharField(max_length=60, verbose_name='E-mail', blank=True, null=True)
	tel_1 = models.CharField(max_length=20, verbose_name='Telefone')
	tel_1_ramal = models.CharField(max_length=10, verbose_name='Ramal', blank=True, null=True)
	tel_2 = models.CharField(max_length=20, verbose_name='Telefone 2', blank=True, null=True)
	tel_2_ramal = models.CharField(max_length=10, verbose_name='Ramal 2', blank=True, null=True)
	tel_fax = models.CharField(max_length=20, verbose_name='Fax',blank=True, null=True)
	valor_maximo_entrega = CurrencyField(max_digits=5,  verbose_name='Valor máximo por entrega', decimal_places=2)
	obs = models.CharField(max_length=200, verbose_name='Obs', blank=True, null=True)
	status = models.IntegerField(max_length=1, verbose_name='Situação', choices=choices.STATUS, default=choices.STATUS_ATIVO)
	status_data = models.DateField(verbose_name='Data situação', blank=True, null=True)

	def produtos_ativos(self):
		return self.produto_set.filter(status=choices.STATUS_ATIVO).order_by('descricao')

	def __unicode__(self):
		return self.razao_social


class Produto(models.Model):
	cliente = models.ForeignKey(Cliente)
	descricao = models.CharField(max_length=120, verbose_name='Descrição')
	status = models.IntegerField(max_length=1, verbose_name='Situação', choices=choices.STATUS, default=choices.STATUS_ATIVO)
	status_data = models.DateField(verbose_name='Data situação', blank=True, null=True)

	def __unicode__(self):
		return self.descricao


class Entregador(models.Model):
	tipo_entregador = models.CharField(max_length=20, verbose_name='Tipo entregador', choices=choices.TIPO_ENTREGADOR)
	cpf_cnpj = models.CharField(max_length=20, verbose_name='CPF/CNPJ')
	nome = models.CharField(max_length=120, verbose_name='Nome/Razão social')
	rg = models.CharField(max_length=20, verbose_name='RG', blank=True, null=True)
	rg_expedicao = models.DateField(verbose_name='Expedição', blank=True, null=True)
	end_rua = models.CharField(max_length=120, verbose_name='Logradouro')
	end_numero = models.CharField(max_length=10, verbose_name='Número', blank=True, null=True)
	end_complemento = models.CharField(max_length=100, verbose_name='Complemento', blank=True, null=True)
	end_bairro = models.CharField(max_length=80, verbose_name='Bairro', blank=True, null=True)
	end_estado = models.CharField(max_length=2, verbose_name='Estado', choices=choices.ESTADOS)
	end_cidade = models.ForeignKey(Cidade, verbose_name='Cidade', blank=True, null=True)
	email = models.CharField(max_length=60, verbose_name='E-mail', blank=True, null=True)
	tel_1 = models.CharField(max_length=20, verbose_name='Telefone')
	tel_1_ramal = models.CharField(max_length=10, verbose_name='Ramal', blank=True, null=True)
	tel_2 = models.CharField(max_length=20, verbose_name='Telefone 2', blank=True, null=True)
	tel_2_ramal = models.CharField(max_length=10, verbose_name='Ramal 2', blank=True, null=True)
	tel_id_radio = models.CharField(max_length=10, verbose_name='ID Nextel', blank=True, null=True)
	banco = models.CharField(max_length=10, verbose_name='Banco', choices=choices.BANCOS)
	agencia = models.CharField(max_length=10, verbose_name='Agência')
	agencia_dv = models.CharField(max_length=4, verbose_name='Agência DV', blank=True, null=True)
	conta = models.CharField(max_length=20, verbose_name='Conta')
	conta_dv = models.CharField(max_length=4, verbose_name='Conta DV', blank=True, null=True)
	categoria_entregador = models.CharField(max_length=80, verbose_name='Categoria entregador', choices=choices.CATEGORIA_ENTREGADOR)
	tipo_entraga = models.CharField(max_length=20, verbose_name='Tipo de entrega', choices=choices.TIPO_ENTREGA)
	pagamento_protocolo = models.BooleanField(verbose_name='Protocolo?', default=False)
	pagamento_protocolo_valor = CurrencyField(max_digits=10,  verbose_name='Valor do protocolo', decimal_places=2, blank=True, null=True)
	cidade_atendida = models.ForeignKey(Cidade, related_name='entregador_atendido', verbose_name='Cidade atendida', blank=True, null=True)
	valor_fixo = CurrencyField(max_digits=10, verbose_name='Valor fixo', decimal_places=2, blank=True, null=True)
	valor_diaria = CurrencyField(max_digits=10, verbose_name='Valor diária', decimal_places=2, blank=True, null=True)
	status = models.IntegerField(max_length=1, verbose_name='Situação', choices=choices.STATUS, default=choices.STATUS_ATIVO)
	status_data = models.DateField(verbose_name='Data situação', blank=True, null=True)
	obs = models.CharField(max_length=200, verbose_name='Obs', blank=True, null=True)

	def __unicode__(self):
		return self.nome


class EntregadorCliente(models.Model):
	entregador = models.ForeignKey(Entregador)
	cliente = models.ForeignKey(Cliente)
	valor = CurrencyField(max_digits=10, verbose_name='Valor', decimal_places=2)

	def __unicode__(self):
		return u'Entregador: {}, Cliente: {}, Valor: {}'.format(self.entregador.nome, self.cliente.razao_social, self.valor)


class Locomocao(models.Model):
	entregador = models.ForeignKey(Entregador)
	tipo_locomocao = models.CharField(max_length=20,verbose_name='Tipo de locomoção', choices=choices.TIPO_LOCOMOCAO)
	combustivel = models.CharField(max_length=20, verbose_name='Combustível', choices=choices.COMBUSTIVEL, blank=True, null=True)
	valor = CurrencyField(max_digits=10, verbose_name='Valor', decimal_places=2)
	mes_ref = models.IntegerField(max_length=2, default=date.today().month)
	ano_ref = models.IntegerField(max_length=4,  default=date.today().year)
	data_pagamento = models.DateField(verbose_name='Data pagamento')
	data_entrega_comprovante = models.DateField(verbose_name='Data entrega da nota', blank=True, null=True)
	situacao_comprovante = models.CharField(max_length=20,verbose_name='Comprovante', choices=choices.STATUS_LOCOMOCAO, default='comp_pendente')
	obs = models.CharField(max_length=200, verbose_name='Obs', blank=True, null=True)

	def __unicode__(self):
		return u'Entegador: {}, Tipo: {}, Combustivel: {}, Valor: {}'.format(self.entregador.nome, self.tipo_locomocao, self.combustivel, self.valor)


class Entrega(models.Model):
	entregador = models.ForeignKey(Entregador)
	saida_data = models.DateField(verbose_name='Data saída', default=date.today())
	retorno_data = models.DateField(verbose_name='Data retorno', blank=True, null=True)
	status = models.CharField(max_length=20, verbose_name='Status da entrega', default=choices.STATUS_ENTREGA[0][0], choices=choices.STATUS_ENTREGA)
	obs = models.CharField(max_length=200, verbose_name='Obs', blank=True, null=True)

	def valor(self):
		valor_total = 0.0
		if self.entregador.categoria_entregador != u'fixo_sem_entrega':
			for entrega_cliente in self.entregacliente_set.all():
				valor = 0.0
				qtd_retorno = entrega_cliente.qtd_retorno if entrega_cliente.qtd_retorno else 0
				qtd = entrega_cliente.qtd_enviada - qtd_retorno

				entregador_cliente = self.entregador.entregadorcliente_set.get(cliente=entrega_cliente.cliente)
				if entregador_cliente:
					valor_total += qtd * float(entregador_cliente.valor)
		return valor_total


class EntregaCliente(models.Model):
	entrega = models.ForeignKey(Entrega)
	cliente = models.ForeignKey(Cliente)
	qtd_enviada = models.IntegerField(max_length=5)
	qtd_retorno = models.IntegerField(max_length=5, default=0, blank=True, null=True)

	def __unicode__(self):
		return u'{} ({})'.format(self.cliente.razao_social, self.qtd_enviada)


class Transferencia(models.Model):
	entregador = models.ForeignKey(Entregador)
	saida_data = models.DateField(verbose_name='Data saída', default=date.today())
	retorno_data = models.DateField(verbose_name='Data retorno', blank=True, null=True)
	destino = models.CharField(max_length=20, verbose_name='Destino', choices=choices.DESTINO_TRANSFERENCIA)
	status = models.CharField(max_length=20, verbose_name='Status da entrega', default=choices.STATUS_ENTREGA[0][0], choices=choices.STATUS_ENTREGA)
	obs = models.CharField(max_length=200, verbose_name='Obs', blank=True, null=True)

	def valor(self):
		valor_total = 0.0
		if self.entregador.categoria_entregador != u'fixo_sem_entrega':
			for transferencia_cliente in self.transferenciacliente_set.all():
				valor = 0.0
				qtd_retorno = transferencia_cliente.qtd_retorno if transferencia_cliente.qtd_retorno else 0

sge/templates/source/base.html
{% extends "base.html" %}
{% load url from future %}

{% block mainmenu %}
    <div class="nav-collapse">
        <ul class="nav">
            {% for item_menu in menu %}
                {% if not item_menu.2 %}
                    <li class=""><a href="{% url item_menu.1 %}">{{ item_menu.0 }}</a></li>
                {% else %}
                    <li class="dropdown">
                        <a href="{% if item_menu.1 %}{% url item_menu.1 %}{% else %}{{ item_menu.1 }}{% endif %}" class="dropdown-toggle" data-toggle="dropdown">{{ item_menu.0 }} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            {% for sub_item_menu in item_menu.2 %}
                                <li><a href="{% if sub_item_menu.1 %}{% url sub_item_menu.1 %}{% else %}{{ sub_item_menu.1 }}{% endif %}">{{ sub_item_menu.0 }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
        <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="icon-user"></i> {{ user.username }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url "source_perfil_alteracao" user.pk %}"><span class="icon-list"></span> Perfil</a></li>
                <li><a href="{% url "source_mudar_senha" %}"><span class="icon-edit"></span> Mudar senha</a></li>
                <li class="divider"></li>
                <li><a href="{% url "auth_logout" %}"><span class="icon-off"></span> Sair</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% if messages  %}
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    {% endif %}
    {% block source-content %}{% endblock %}
    <footer>
        <p>&copy; SGE 2012</p>
    </footer>
{% endblock %}

sge/templates/source/cliente_alteracao.html
{% extends "source/base.html" %}

{% block modals %}
    <div id="dlg-confirm-remover-produto" class="modal fade">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Remover produto</h3>
        </div>
        <div class="modal-body">
            <p>Você tem certeza que deseja remover o produto?</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Não</a>
            <a href="#" id="bt-remover-produto" class="btn btn-danger">Sim</a>
        </div>
    </div>
{% endblock %}

{% block source-content %}
    <h3>Alteração de clientes</h3>
    <form method="post" class="form-horizontal" action="{% url source_cliente_alteracao cliente.pk %}">
        {% csrf_token %}
        <div class="tabbable">
            <ul id="tab-navegation" class="nav nav-pills">
                <li id="tab-dados-principais" class="active">
                    <a href="#dados-principais" data-toggle="tab">Dados principais</a>
                </li>
                <li id="tab-produtos">
                    <a href="#produtos" data-toggle="tab">Produtos {% if cliente.produtos_ativos.count %}({{ cliente.produtos_ativos.count }}){% endif %}</a>
                </li>
            </ul>
            <div id="tab-pane-navegation" class="tab-content">
                <div class="tab-pane active" id="dados-principais">
                    <div class="control-group {% if form.cnpj.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.cnpj.auto_id }}">{{ form.cnpj.label }}</label>
                        <div class="controls">
                            {{ form.cnpj }}
                            {% if form.cnpj.errors %}<span class="help-inline">{{ form.cnpj.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.razao_social.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.razao_social.auto_id }}">{{ form.razao_social.label }}</label>
                        <div class="controls">
                            {{ form.razao_social }}
                            {% if form.razao_social.errors %}<span class="help-inline">{{ form.razao_social.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.end_rua.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.end_rua.auto_id }}">{{ form.end_rua.label }}</label>
                        <div class="controls">
                            {{ form.end_rua }}
                            {% if form.end_rua.errors %}<span class="help-inline">{{ form.end_rua.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.end_numero.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.end_numero.auto_id }}">{{ form.end_numero.label }}</label>
                        <div class="controls">
                            {{ form.end_numero }}
                            {{ form.end_complemento }}
                            {% if form.end_numero.errors %}<span class="help-inline">{{ form.end_numero.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.end_bairro.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.end_bairro.auto_id }}">{{ form.end_bairro.label }}</label> 
                        <div class="controls">
                            {{ form.end_bairro }}
                            {% if form.end_bairro.errors %}<span class="help-inline">{{ form.end_bairro.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.end_estado.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.end_estado.auto_id }}">{{ form.end_estado.label }}</label> 
                        <div class="controls">
                            {{ form.end_estado }}
                            {% if form.end_estado.errors %}<span class="help-inline">{{ form.end_estado.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.end_cidade.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.end_cidade.auto_id }}">{{ form.end_cidade.label }}</label> 
                        <div class="controls">
                            {{ form.end_cidade }}
                            {% if form.end_cidade.errors %}<span class="help-inline">{{ form.end_cidade.errors.as_text }}</span>{% endif %}
                        </div>
                    </div>
                    <div class="control-group {% if form.email.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.email.auto_id }}">{{ form.email.label }}</label> 
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on">@</span>
                                {{ form.email }}
                                {% if form.email.errors %}<span class="help-inline">{{ form.email.errors.as_text }}</span>{% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="{{ form.tel_1.auto_id }}">{{ form.tel_1.label }}</label> 
                        <div class="controls">
                            <span class="control-group {% if form.tel_1.errors %}error{% endif %}">{{ form.tel_1 }}</span>
                            {{ form.tel_1_ramal }}
                            <span class="control-group {% if form.tel_1.errors %}error{% endif %}">
                                {% if form.tel_1.errors %}<span class="help-inline">* O telefone é obrigatório</span>{% endif %}
                            </span>                         
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="{{ form.tel_2.auto_id }}">{{ form.tel_2.label }}</label> 
                        <div class="controls">
                            {{ form.tel_2 }} {{ form.tel_2_ramal }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="{{ form.tel_fax.auto_id }}">{{ form.tel_fax.label }}</label> 
                        <div class="controls">
                            {{ form.tel_fax }}
                        </div>
                    </div>
                    <div class="control-group {% if form.valor_maximo_entrega.errors %}error{% endif %}">
                        <label class="control-label" for="{{ form.valor_maximo_entrega.auto_id }}">{{ form.valor_maximo_entrega.label }}</label> 
                        <div class="controls">
                            <div class="input-prepend">
                                <span class="add-on">R$</span>
                                {{ form.valor_maximo_entrega }}
                                {% if form.valor_maximo_entrega.errors %}<span class="help-inline">{{ form.valor_maximo_entrega.errors.as_text }}</span>{% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="{{ form.status.auto_id }}">{{ form.status.label }}</label> 
                        <div class="controls">
                            {{ form.status }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="{{ form.obs.auto_id }}">{{ form.obs.label }}</label> 
                        <div class="controls">
                            {{ form.obs }}
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="produtos">
                    <div>
                        {{ clienteproduto_formset.management_form }}
                        <button id="bt-adicionar-linha-produto" type="button" class="btn btn-small">
                            <i class="icon-plus"></i>
                            <span>Adicionar</span>
                        </button><br /><br />
                        <table id="tb-produtos" class="table table-bordered">
                            <tbody>
                                {% for clienteproduto_form in clienteproduto_formset %}
                                <tr>
                                    <td class="control-group {% if clienteproduto_form.descricao.errors %}error{% endif %}">
                                        {{ clienteproduto_form.descricao }}
                                        {% for hidden_field in clienteproduto_form.hidden_fields %}{{ hidden_field }}{% endfor %}
                                        <span class="control-group {% if clienteproduto_form.descricao.errors %}error{% endif %}">
                                            {% if clienteproduto_form.descricao.errors %}<span class="help-inline">* Informe o nome do produto.</span>{% endif %}
                                        </span>
                                    </td>
                                    <td width="16px" style="vertical-align: middle">
                                        <a class="icon-trash" href="#"></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-large btn-success">Salvar</button>
            <a href="{% url source_cliente_consulta %}" class="btn btn-large btn-primary">Voltar</a>
        </div>
    </form>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}js/lib/jquery.price_format.js"></script>
    <script src="{{ STATIC_URL }}js/lib/jquery.maskedinput-1.3.min.js"></script>
    <script src="{{ STATIC_URL }}js/scripts/cliente.js"></script>
{% endblock %}

sge/templates/source/entregador_consulta.html
{% extends "source/base.html" %}

{% block modals %}
	<div id="confirm" class="modal hide fade">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Atenção!</h3>
		</div>
		<div class="modal-body"></div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Não</a>
			<a href="#" id="bt-confirm" class="btn">Sim</a>
		</div>
	</div>
	<div id="desativar-entregador" class="modal hide fade">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>Atenção!</h3>
		</div>
		<div class="modal-body"></div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Não</a>
			<a href="#" id="bt-action" class="btn">Sim</a>
		</div>
	</div>
{% endblock %}

{% block source-content %}	
	<h3>Entregadores</h3>
	<table id="tb-entregador-consulta" class="table table-bordered sge clickable">
		<thead>
			<tr>
				<th>Entregador</th>
				<th width="200px">CPF/CNPJ</th>
				<th width="200px">Categoria</th>
				<th width="120px">Clientes</th>
				<th width="16px"></th>
			</tr>
		</thead>
		<tbody>
		{% for entregador in entregadores %}
			<tr url-edit="{% url source_entregador_alteracao entregador.pk %}" 
				{% if not entregador.status %}
					url-status-change="{% url source_status_change entregador.pk 1 %}" 
				{% else %}
					url-status-change="{% url source_status_change entregador.pk 0 %}" 
				{% endif %}
				class="{% if not entregador.status %}red-font activate{% else %}desactivate{% endif %}">
				<td class="entregador_nome">{{ entregador.nome }}</td>
				<td>{{ entregador.cpf_cnpj }}</td>
				<td>{{ entregador.get_categoria_entregador_display }}</td>
				<td>
					{{ entregador.entregadorcliente_set.count }}
				</td>
				<td class="status">
					<span class="{% if not entregador.status %}icon-ok{% else %}icon-trash{% endif %}"></span>
				</td>
			</tr>
		{% empty %}
            <tr>
                <td colspan="4" class="no-action">Nenhum entregador incluído.</td>
            </tr>
        {% endfor %}
		</tbody>
	</table>
{% endblock %}

{% block js %}
	<script src="{{ STATIC_URL }}js/lib/jquery.maskedinput-1.3.min.js"></script>
	<script src="{{ STATIC_URL }}js/scripts/entregador.js"></script>
{% endblock %}